version: "3"

services:
  api:
    build:
      context: ./daw.aa.supply_chain_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./config.yml:/opt/config.yml"
    restart: always
    depends_on:
      - mysqldb

  dash_builder:
    build:
      context: ./daw.aa.supply_chain_dash
      dockerfile: Dockerfile
    restart: "no"
    command: ["bash", "-c", "rm -rf /build/* && cp -r /app/* /build"]
    volumes:
      - dash_build:/build

  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "mysqldb:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_DATABASE: "daw_aa_supply_chain_api"

  reverse_proxy:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - dash_build:/www/dash
      - "./ngix/default.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/ssl/private:/etc/ssl/certs/nginx/"

volumes:
  dash_build:
  mysqldb: