db: sqlite+aiosqlite://
# db: sqlite+aiosqlite:///dev.db
jwt_key: XHXiMplg/B5amwdN8zP4cAqwP4WhyzG8u28sYiMJoZM=
api:
  host: 0.0.0.0
  port: 8000
cors:
  allow_origins:
    - http://localhost:3001
  allow_methods:
    - "*"
  allow_headers:
    - "*"
  allow_credentials: true
redirects:
  invalid_uid: /invalid